############################################
# yaml使用缩进表示层级，以两个空格来控制，
# 不能使用TAB
############################################
config:
  # 执行输出是否需要被记录到日志文件中。
  # 在ruby的yaml库中，on 和 true 同义，off 和 false 同义
  sshlog: on
  # 批量执行命令的并发量
  thread_concurrency: 10
database:
  db_host: "127.0.0.1"
  db_user: "root"
  db_schema: "auto_op2"
  db_pwd:  ""


